### ISSUE TITLE
Add admin create and delete resource API functions

### ISSUE THREAD

**Issue by Nico26-sw** [flowthings/datahub#18]
To allow Octave applications re-architecture without breaking change of the resource tree, we need to be able to create and delete resources in a given namespace.

API functions to create

- `admin_CreateInput`
- `admin_CreateOutput`
- `admin_DeleteResource`

Those API functions will also be required

- `admin_SetJsonExample`
- `admin_MarkOptional`

**Comment by jtchitty** [comment]
Why does the re-architecture need these new functions?

**Comment by jvermillard** [comment]
https://confluence.sierrawireless.com/display/BROOKLYN/Edge+processing+re-architecture

merge virtual, orp, timer, ar and keep the same layout

**Comment by jtchitty** [comment]
Understood. I'm wondering if it might be better to have a "relocate" feature (or some better-named feature) that allows the admin API to be used to set up a translation from one resource path to another.  There has been talk of an "alias" feature for quite some time, to address the same sort of problem (that resources appear in different places on different machines, depending on what apps implement them).  Or, we could just allow users of the I/O API to specify an absolute path for their resources, and then assign ownership of namespaces based on a first-come-first-served basis.
